### ISSUE TITLE
need informations

### ISSUE THREAD

**Issue by gilcot** [verdel/teampass-cli#2]
Hello,

Against what version of teampass your package is tested ?

Also, you wrote in the readme:
> To use the teampass-cli, you need to modify the file api/functions.php on the server there Teampass was installed. The modified version of the file api/functions.php is located in the lib folder.

Well, but what are the modification to make ?

**Comment by verdel** [comment]
Please forgive me for the long answer time.

At the moment we are using Teampass version 2.1.27.35. teampass-cli and a modified version of _functions.php_ is tested with this version of Teampass.

The current actual release of Teampass is 2.1.27.36. In this release, the developer contributed to functions.php minimal changes. Therefore, the version of the _functions.php_ from my repository will work without problems also with version 2.1.27.36.

In any case, I will soon synchronize the code of my version with the upstream version.

As for the changes in the functions file.changes that have been made by me:
**API methods have been added to the function _restGet()_:**
1. For CLI **list** sub-command:
- /list/folders
- /list/items

2. Get item and folder by ID:
- /get/item/{item_id}
- /get/folder/{folder_id}

3. Search item and folder by Title:
- /find/items/{item_title}
- /find/items/{folder_title}

**Comment by gilcot** [comment]
Thanks for the reply. 

Please add to the README that your are using the second version of the API and it's know to work from 2.1.27.35 ...

I'm waiting to patch our installation (or will it work with the original file?)

**Comment by verdel** [comment]
I have added additional information to the README file. I also synced the base code of functions.php outside of my edits with the upstream version from Teampass repository.

> I'm waiting to patch our installation (or will it work with the original file?)

You need to patch your installation anyway to use teampass-cli.

**Comment by gilcot** [comment]
Great. Thanks.
