### ISSUE TITLE
tpcli edit doesn't work

### ISSUE THREAD

**Issue by thejulu** [verdel/teampass-cli#3]
# tpcli --api-endpoint http://teampass.example.com/api/index.php --api-key xxxxxxxxxxxxxxxxxxxxxxx edit --id 31 --title test.tpcli --login root --password password --folder-id 18
Error: Label or Password or Folder ID is missing

hi there, 
i've got no clue what i'm doing wrong here - the same works flawlessly with list, search and add, only edit doesn't want to work... and advice what i'm doing wrong here?
thanks in advance,
julu

@verdel - i've tried to reupload the function.php, but that doesn't fix the issue. currently running 2.1.27, could that be the issue?

**Comment by verdel** [comment]
Hi!
Unfortunately, this project was originally conceived to simplify the work with the password database in my main job. I have now changed jobs and no longer use teampass. I will try to find the time as quickly as possible to understand the reasons for your problem.

**Comment by thejulu** [comment]
hey, no problem at all, i know the drill... if i manage to decypher the issue from the code i'll gladly post it here...

**Comment by verdel** [comment]
I found that I didn't send some changes to the code to the repository. Try changing the entry in Teampass, after updating the teampass-cli. At least I managed to change the record now.

**Comment by thejulu** [comment]
works flawlessly, thanks a lot!
